// Editable public copy. Selectors are scoped to public markup and never accept user HTML.
window.ALASH_COPY_FIELDS = [
 // group, label, CSS selector(s), initial text, optional mode
 ['Общее','Подпись логотипа','.identity[href="#home"] small','LEAGUE'],
 ['Общее','Меню: Главная','.menu-links a[href="#home"] span:nth-child(2), .bottom-nav a[href="#home"] span','Главная'],
 ['Общее','Меню: Рейтинг','.menu-links a[href="#rankings"] span:nth-child(2), .bottom-nav a[href="#rankings"] span, .desktop-nav a[href="#rankings"]','Рейтинг'],
 ['Общее','Меню: Бойцы','.menu-links a[href="#fighters"] span:nth-child(2), .bottom-nav a[href="#fighters"] span, .desktop-nav a[href="#fighters"]','Бойцы'],
 ['Общее','Меню: Чемпионы','.menu-links a[href="#champions"] span:nth-child(2), .desktop-nav a[href="#champions"]','Чемпионы'],
 ['Общее','Меню: Турниры','.menu-links a[href="#events"] span:nth-child(2), .bottom-nav a[href="#events"] span, .desktop-nav a[href="#events"]','Турниры'],
 ['Общее','Меню: Новости','.menu-links a[href="#news"] span:nth-child(2), .desktop-nav a[href="#news"]','Новости'],
 ['Общее','Меню: Видео','.menu-links a[href="#video"] span:nth-child(2)','Видео'],
 ['Общее','Меню: Результаты','.menu-links a[href="#results"] span:nth-child(2)','Результаты'],
 ['Общее','Меню: О лиге','.menu-links a[href="#about"] span:nth-child(2)','О лиге'],
 ['Общее','Нижнее меню: Ещё','.bottom-nav .more-menu span','Ещё'],
 ['Общее','Кнопка билетов в меню','#site-menu > .primary-button','БИЛЕТЫ НА ТУРНИР ','first'],
 ['Общее','Подпись над заголовками страниц','.page-heading .eyebrow','ALASH PRIDE LEAGUE'],
 ['Общее','Ссылка на админку','.site-footer a[href="admin.html"]','УПРАВЛЕНИЕ САЙТОМ ↗'],
 ['Общее','Подпись внизу сайта','.site-footer > span','© 2026 ALASH PRIDE LEAGUE'],
 ['Главная','Надпись над баннером','.home-hero .eyebrow','KAZAKHSTAN MMA LEAGUE'],
 ['Главная','Главный заголовок','.home-hero h1','ALASH PRIDE','first'],
 ['Главная','Слоган','.home-hero h1 span','СИЛА. ЧЕСТЬ. НАСЛЕДИЕ.'],
 ['Главная','Кнопка рейтинга','.home-hero .primary-button','СМОТРЕТЬ РЕЙТИНГИ','first'],
 ['Главная','Заголовок турнира','.next-tournament .eyebrow','СЛЕДУЮЩИЙ ТУРНИР'],
 ['Главная','Название турнира','.next-tournament h2','ALASH PRIDE · СЕМЕЙ'],
 ['Главная','Дата турнира','.next-tournament p','Декабрь 2026 ','first'],
 ['Главная','Страна турнира','.next-tournament p',' Казахстан','last'],
 ['Главная','Быстрая ссылка: рейтинг','.quick-links a[href="#rankings"]','Рейтинг','last'],
 ['Главная','Быстрая ссылка: бойцы','.quick-links a[href="#fighters"]','Бойцы','last'],
 ['Главная','Быстрая ссылка: турниры','.quick-links a[href="#events"]','Турниры','last'],
 ['Главная','Быстрая ссылка: новости','.quick-links a[href="#news"]','Новости','last'],
 ['Главная','Последние бои','.home-below .section-title h2','ПОСЛЕДНИЕ БОИ'],
 ['Главная','Первое видео: заголовок','.home-videos a:first-child h3','РЕЗУЛЬТАТ ГЛАВНОГО БОЯ'],
 ['Главная','Первое видео: подпись','.home-videos a:first-child p','Alash Pride 132'],
 ['Главная','Второе видео: заголовок','.home-videos a:nth-child(2) h3','В ЦЕНТРЕ СОБЫТИЙ'],
 ['Главная','Второе видео: подпись','.home-videos a:nth-child(2) p','Alash Pride TV ↗'],
 ['Главная','Блок рейтинга: подпись','.home-rating-link .eyebrow','ПУТЬ К ПОЯСУ'],
 ['Главная','Блок рейтинга: заголовок','.home-rating-link h2','ВЕРШИНА — ОДНА.'],
 ['Главная','Блок рейтинга: текст','.home-rating-link p','Чемпионы и претенденты каждой весовой категории.'],
 ['Главная','Блок рейтинга: кнопка','.home-rating-link a','ЧЕМПИОНЫ ЛИГИ →'],
 ['Рейтинг','Заголовок','.page-heading h1','РЕЙТИНГ БОЙЦОВ'],
 ['Рейтинг','Подзаголовок','.page-heading > p:last-child','Чемпион и десять претендентов в каждой весовой'],
 ['Рейтинг','Пустое место','.rank-table .unfilled td:nth-child(2)','Будет объявлен'],
 ['Рейтинг','Вакантный пояс','.champion-card.vacant h3','Скоро объявим'],
 ['Бойцы','Заголовок','.page-heading h1','БОЙЦЫ'],
 ['Бойцы','Подзаголовок','.page-heading > p:last-child','Лица Alash Pride. Характер за каждым именем.'],
 ['Бойцы','Поиск: подсказка','#fighter-search','Поиск бойца…','placeholder'],
 ['Бойцы','Фото не добавлено','.photo-pending','ФОТО СКОРО'],
 ['Бойцы','Нет результатов: заголовок','.empty-state h2','Бойцы не найдены'],
 ['Бойцы','Нет результатов: пояснение','.empty-state p','Попробуйте другое имя или сбросьте фильтры.'],
 ['Чемпионы','Заголовок','.page-heading h1','ЧЕМПИОНЫ ЛИГИ'],
 ['Чемпионы','Подзаголовок','.page-heading > p:last-child','Один пояс. Одна вершина. Каждая весовая.'],
 ['Чемпионы','Пустая категория','.vacant-row h2','Скоро объявим'],
 ['Новости','Заголовок','.page-heading h1','НОВОСТИ'],
 ['Новости','Подзаголовок','.page-heading > p:last-child','Последние события Alash Pride'],
 ['Новости','Главная новость: рубрика','.news-lead .eyebrow','СЛЕДУЮЩИЙ ТУРНИР'],
 ['Новости','Главная новость: заголовок','.news-lead h2','ALASH PRIDE В СЕМЕЕ'],
 ['Новости','Главная новость: текст','.news-lead p','Декабрь 2026. Точная дата, арена и кард будут объявлены дополнительно.'],
 ['Новости','Главная новость: ссылка','.news-lead .text-link','ИНФОРМАЦИЯ И БИЛЕТЫ →'],
 ['Новости','Вторая новость: дата','.news-row > span','29.10.2025'],
 ['Новости','Вторая новость: заголовок','.news-row h2 a','Миллион подписчиков Alash Pride TV ↗'],
 ['Новости','Вторая новость: текст','.news-row p','История золотой кнопки YouTube — на Offside.kz.'],
 ['Новости','Ссылка на Instagram','.page > .primary-button','НОВОСТИ В INSTAGRAM ','first'],
 ['Турниры','Заголовок','.events-section .section-heading h2','ТУРНИРЫ'],
 ['Турниры','Будущий турнир: статус','.upcoming-card .event-state','ПРЕДСТОЯЩИЙ'],
 ['Турниры','Будущий турнир: год','.upcoming-card .card-top span:last-child','2026'],
 ['Турниры','Будущий турнир: название','.upcoming-card .card-title h3','ALASH PRIDE','first'],
 ['Турниры','Будущий турнир: город','.upcoming-card .card-title h3 span','СЕМЕЙ'],
 ['Турниры','Будущий турнир: месяц','.upcoming-card .card-date','ДЕКАБРЬ'],
 ['Турниры','Будущий турнир: место','.upcoming-card > p','Семей, Казахстан'],
 ['Турниры','Будущий турнир: кнопка','.upcoming-card .card-action','БИЛЕТЫ — СКОРО'],
 ['Турниры','Турнир 132: город','.event-card[data-status="past"]:nth-child(2) h3 span','ШЫМКЕНТ'],
 ['Турниры','Турнир 132: дата','.event-card[data-status="past"]:nth-child(2) .card-date','30 СЕНТЯБРЯ'],
 ['Турниры','Турнир 132: бой','.event-card[data-status="past"]:nth-child(2) > p','Жасия — Маратбек уулу'],
 ['Турниры','Турнир 128: город','.event-card[data-status="past"]:nth-child(3) h3 span','ЭКИБАСТУЗ'],
 ['Турниры','Турнир 128: дата','.event-card[data-status="past"]:nth-child(3) .card-date','28 АВГУСТА'],
 ['Турниры','Турнир 128: бой','.event-card[data-status="past"]:nth-child(3) > p','Хатаев — Оливейра'],
 ['Турниры','Турнир 127: город','.event-card[data-status="past"]:nth-child(4) h3 span','ШЫМКЕНТ'],
 ['Турниры','Турнир 127: дата','.event-card[data-status="past"]:nth-child(4) .card-date','18 ИЮЛЯ'],
 ['Турниры','Турнир 127: бой','.event-card[data-status="past"]:nth-child(4) > p','Абдималик уулу — Бутко'],
 ['Турниры','Турнир 132: название','.event-card:nth-child(2) h3','ALASH PRIDE','first'],
 ['Турниры','Турнир 132: статус','.event-card:nth-child(2) .event-state','ЗАВЕРШЁН'],
 ['Турниры','Турнир 132: ссылка','.event-card:nth-child(2) .card-action','РЕЗУЛЬТАТ ГЛАВНОГО БОЯ'],
 ['Турниры','Турнир 128: название','.event-card:nth-child(3) h3','ALASH PRIDE','first'],
 ['Турниры','Турнир 128: статус','.event-card:nth-child(3) .event-state','ЗАВЕРШЁН'],
 ['Турниры','Турнир 128: ссылка','.event-card:nth-child(3) .card-action','КАРД НА SHERDOG'],
 ['Турниры','Турнир 127: название','.event-card:nth-child(4) h3','ALASH PRIDE','first'],
 ['Турниры','Турнир 127: статус','.event-card:nth-child(4) .event-state','ЗАВЕРШЁН'],
 ['Турниры','Турнир 127: ссылка','.event-card:nth-child(4) .card-action','РЕЗУЛЬТАТЫ НА SHERDOG'],
 ['Билеты','Рубрика','.ticket-title .label','БИЛЕТЫ НА ТУРНИР'],
 ['Билеты','Заголовок','.ticket-title h2','ALASH PRIDE ','first'],
 ['Билеты','Город','.ticket-title h2 span','СЕМЕЙ'],
 ['Билеты','Статус','.ticket-copy strong','Продажа скоро'],
 ['Билеты','Информация','.ticket-copy p','Цены, схема мест и ссылка на покупку появятся после официального старта продаж.'],
 ['Билеты','Кнопка','.tickets-section .button','АНОНСЫ ЛИГИ'],
 ['Результаты','Заголовок','.results-section .section-heading h2','ПОСЛЕДНИЙ РЕЗУЛЬТАТ'],
 ['Результаты','Турнир и дата','.results-section .section-heading .label','ALASH PRIDE 132 · 30.09.2026'],
 ['Результаты','Победитель','.result-board .winner h3','БЕКЗАТ ЖАСИЯ'],
 ['Результаты','Проигравший','.result-board .opponent h3','АРГЕН МАРАТБЕК УУЛУ'],
 ['Результаты','Вес и статус','.result-center .weight','ТИТУЛЬНЫЙ БОЙ · ЛЕГЧАЙШИЙ ВЕС'],
 ['Результаты','Исход боя','.result-center strong','KO'],
 ['Результаты','Раунд','.result-center span:last-of-type','1 РАУНД'],
 ['Результаты','Описание','.result-center p','Защита чемпионского пояса'],
 ['Результаты','Страна победителя','.result-board .winner .country','КАЗАХСТАН'],
 ['Результаты','Страна соперника','.result-board .opponent .country','КЫРГЫЗСТАН'],
 ['Результаты','Статус победителя','.result-board .winner .win-tag','ПОБЕДИТЕЛЬ'],
 ['Результаты','Статус соперника','.result-board .opponent .loss-tag','ПОРАЖЕНИЕ'],
 ['Результаты','Ссылка на обзор','.results-section .source-link','Обзор и видео боя на Sports.kz'],
 ['Видео','Заголовок','.video-section .section-heading h2','ALASH PRIDE TV'],
 ['Видео','Видео: ссылка','.video-section .section-link:first-of-type','ВСЕ ВИДЕО НА YOUTUBE'],
 ['Видео','Подпись к видео','.video-caption','ПОЛНЫЕ БОИ И ТРАНСЛЯЦИИ'],
 ['Видео','История: дата','.media-stories article:first-child .label','НОВОСТИ ЛИГИ · 29.10.2025'],
 ['Видео','История: заголовок','.media-stories article:first-child h3','ALASH PRIDE TV: МИЛЛИОН ПОДПИСЧИКОВ'],
 ['Видео','История: текст','.media-stories article:first-child p','Канал лиги преодолел миллионную отметку и получил золотую кнопку YouTube.'],
 ['Видео','История: ссылка','.media-stories article:first-child a','ЧИТАТЬ НА OFFSIDE.KZ'],
 ['Видео','Заметка: рубрика','.media-stories article:nth-child(2) .label','ОФИЦИАЛЬНЫЕ КАНАЛЫ'],
 ['Видео','О лиге: ссылка','.media-stories article:first-child .section-link','ЧИТАТЬ НА OFFSIDE.KZ'],
 ['О лиге','Название','.about-section h2','ALASH PRIDE LEAGUE'],
 ['О лиге','Описание','.about-section p','Казахстанская лига смешанных единоборств. История Alash Pride началась в 2011 году. За это время лига провела более ста турниров с участием бойцов из Казахстана и других стран.'],
 ['О лиге','Ссылка на историю','.about-section .section-link','ИСТОРИЯ ЛИГИ'],
 ['О лиге','Частые вопросы: заголовок','.faq-section > h2','ЗРИТЕЛЯМ'],
 ['О лиге','Вопрос 1','.faq-list details:nth-child(1) summary','Когда и где пройдёт турнир в Семее?'],
 ['О лиге','Ответ 1','.faq-list details:nth-child(1) p','Турнир запланирован на декабрь 2026 года. Точная дата, время начала и арена будут объявлены дополнительно.'],
 ['О лиге','Вопрос 2','.faq-list details:nth-child(2) summary','Как купить билет?'],
 ['О лиге','Ответ 2','.faq-list details:nth-child(2) p','Старт продаж пока не объявлен. После его подтверждения в разделе «Билеты» появится ссылка на покупку и информация о местах.'],
 ['О лиге','Вопрос 3','.faq-list details:nth-child(3) summary','Кто выступит на турнире?'],
 ['О лиге','Ответ 3','.faq-list details:nth-child(3) p','Кард турнира в Семее готовится к анонсу. Подтверждённые пары появятся на сайте после объявления.']
].map(([group,label,selector,original,mode='text'],i)=>({key:`copy-${i}`,group,label,selector,original,mode}));
